---
# Metrics Collection Configuration
version: "1.0.0"
created: "2025-09-18"
last_updated: "2025-09-18"
status: "active"

# Collection Settings
collection:
  enabled: true
  level: "detailed"  # basic|detailed|debug
  async: true        # Non-blocking collection

  # What to collect
  collectors:
    commands: true
    agents: true
    scripts: true
    workflows: true

  # Storage configuration
  storage:
    location: ".claude/metrics/"
    retention_days: 90
    max_size_mb: 100
    rotation: "daily"

  # Performance settings
  performance:
    batch_size: 10
    flush_interval_seconds: 30
    max_memory_mb: 50
    sampling_rate: 1.0  # 0.0-1.0, 1.0 = collect everything

# Privacy & Security
privacy:
  anonymize_paths: false
  exclude_patterns:
    - "*.secret"
    - "*.key"
    - "*token*"
  hash_user_data: false

# Data Schema Version
schema_version: "1.0.0"

# Export Settings
export:
  formats: ["json", "csv", "yaml"]
  default_format: "json"
  include_raw_data: true

# Analytics Configuration
analytics:
  enable_correlations: true
  enable_predictions: false
  min_data_points: 10
  confidence_threshold: 0.8